#cloud-config
package_update: true
packages:
  - curl

runcmd:
  - [ bash, -lc, "curl -fsSL https://raw.githubusercontent.com/0denko/AstroDrive/main/deploy/install.sh | bash -s -- https://github.com/0denko/AstroDrive" ]
